# Generated by Django 4.2.23 on 2025-10-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('livreur', 'Livreur'), ('resp_livraison', 'Responsable Livraison'), ('vendeur', 'Vendeur/Vendeuse'), ('resp_ventes', 'Responsable Ventes'), ('cuisinier', 'Cuisinier'), ('resp_dept_cuisine', 'Responsable Département Cuisine'), ('chef_cuisine', 'Chef Cuisine'), ('chef_commande', 'Chef Commande'), ('maitre_hotel', "Maître d'Hôtel"), ('comptable', 'Comptable'), ('verificateur_checklist', 'Vérificateur Checklist'), ('admin', 'Administrateur')], max_length=30),
        ),
    ]
