# Generated by Django 4.2.23 on 2025-10-06 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieObjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('icone', models.CharField(blank=True, help_text='Classe FontAwesome (ex: fa-utensils)', max_length=50)),
                ('couleur', models.CharField(default='slate', help_text='Couleur Tailwind', max_length=20)),
                ('ordre', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Catégorie d'objet",
                'verbose_name_plural': "Catégories d'objets",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('numero_commande', models.CharField(blank=True, help_text='Pour lier à une livraison', max_length=100)),
                ('date_evenement', models.DateField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de vérification'), ('en_cours', 'En cours de vérification'), ('validee', 'Validée'), ('incomplete', 'Incomplète')], default='brouillon', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('notes_verificateur', models.TextField(blank=True)),
                ('creee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_creees', to=settings.AUTH_USER_MODEL)),
                ('verificateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_verifiees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
                'ordering': ['-date_evenement', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ObjetChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unite', models.CharField(default='unité', help_text='Ex: unité, kg, L, paire', max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objets', to='ventes.categorieobjet')),
            ],
            options={
                'verbose_name': 'Objet de checklist',
                'verbose_name_plural': 'Objets de checklist',
                'ordering': ['categorie', 'ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('ordre', models.IntegerField(default=0)),
                ('verifie', models.BooleanField(default=False)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventes.checklist')),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventes.objetchecklist')),
                ('verifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de checklist',
                'verbose_name_plural': 'Items de checklist',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
