# Generated by Django 4.2.23 on 2025-10-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='numero_commande',
            field=models.CharField(help_text='Pour lier à une livraison', max_length=20, unique=True),
        ),
    ]
