# Generated by Django 4.2.23 on 2025-10-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_alter_checklist_numero_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchecklist',
            name='statut_verification',
            field=models.CharField(choices=[('non_verifie', 'Non vérifié'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='non_verifie', max_length=20),
        ),
    ]
