# Generated by Django 4.2.23 on 2025-10-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_itemchecklist_statut_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchecklist',
            name='modifie_depuis_verification',
            field=models.BooleanField(default=False, help_text="Indique si l'item a été modifié par les Ventes après vérification"),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de vérification'), ('en_cours', 'En cours de vérification'), ('validee', 'Validée'), ('incomplete', 'Incomplète')], default='en_cours', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemchecklist',
            name='statut_verification',
            field=models.CharField(choices=[('non_verifie', 'Non vérifié'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='non_verifie', help_text="Statut de vérification de l'item", max_length=20),
        ),
        migrations.AlterField(
            model_name='itemchecklist',
            name='verifie',
            field=models.BooleanField(default=False, help_text='Garder pour compatibilité - synchro auto avec statut'),
        ),
    ]
