# Generated by Django 4.2.23 on 2025-10-07 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventes', '0004_itemchecklist_modifie_depuis_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemchecklist',
            name='statut_verification',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_cours', help_text="Statut de vérification de l'item", max_length=20),
        ),
        migrations.AlterField(
            model_name='itemchecklist',
            name='verifie',
            field=models.BooleanField(default=False, help_text='Synchro auto avec statut'),
        ),
        migrations.CreateModel(
            name='ItemChecklistHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_avant', models.DecimalField(blank=True, decimal_places=2, help_text='Quantité avant modification', max_digits=10, null=True)),
                ('quantite_apres', models.DecimalField(decimal_places=2, help_text='Quantité après modification', max_digits=10)),
                ('type_modification', models.CharField(choices=[('quantite', 'Quantité modifiée'), ('ajout', 'Item ajouté'), ('suppression', 'Item supprimé')], default='quantite', max_length=20)),
                ('date_modification', models.DateTimeField(auto_now_add=True, help_text='Date et heure de la modification')),
                ('notes', models.TextField(blank=True, help_text='Notes sur la modification')),
                ('item', models.ForeignKey(help_text='Item concerné par la modification', on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='ventes.itemchecklist')),
                ('modifie_par', models.ForeignKey(blank=True, help_text='Utilisateur qui a fait la modification', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de modification',
                'verbose_name_plural': 'Historiques de modifications',
                'ordering': ['-date_modification'],
                'indexes': [models.Index(fields=['item', '-date_modification'], name='ventes_item_item_id_4359ca_idx')],
            },
        ),
    ]
