# Generated by Django 4.2.23 on 2025-10-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0005_alter_itemchecklist_statut_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetchecklist',
            name='quantite',
            field=models.IntegerField(default=0, help_text='Quantité en stock'),
        ),
    ]
