# Generated by Django 4.2.23 on 2025-10-07 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0007_alter_livraison_checklist'),
        ('ventes', '0006_objetchecklist_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='livraison.livraison'),
        ),
    ]
