# Generated by Django 4.2.23 on 2025-10-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0007_checklist_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchecklisthistorique',
            name='categorie_nom',
            field=models.CharField(blank=True, help_text='Nom de la catégorie', max_length=100),
        ),
        migrations.AddField(
            model_name='itemchecklisthistorique',
            name='checklist',
            field=models.ForeignKey(help_text='Checklist à laquelle appartient cet item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_items', to='ventes.checklist'),
        ),
        migrations.AddField(
            model_name='itemchecklisthistorique',
            name='objet_nom',
            field=models.CharField(blank=True, help_text="Nom de l'objet (sauvegardé en cas de suppression)", max_length=200),
        ),
        migrations.AddField(
            model_name='itemchecklisthistorique',
            name='objet_unite',
            field=models.CharField(blank=True, help_text="Unité de l'objet", max_length=50),
        ),
        migrations.AddIndex(
            model_name='itemchecklisthistorique',
            index=models.Index(fields=['checklist', '-date_modification'], name='ventes_item_checkli_ce2a27_idx'),
        ),
    ]
