# Generated by Django 4.2.23 on 2025-10-10 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0008_itemchecklisthistorique_categorie_nom_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='itemchecklisthistorique',
            name='ventes_item_item_id_4359ca_idx',
        ),
        migrations.AlterField(
            model_name='itemchecklisthistorique',
            name='categorie_nom',
            field=models.CharField(help_text='Nom de la catégorie', max_length=100),
        ),
        migrations.AlterField(
            model_name='itemchecklisthistorique',
            name='checklist',
            field=models.ForeignKey(help_text='Checklist à laquelle appartient cet item', on_delete=django.db.models.deletion.CASCADE, related_name='historique_items', to='ventes.checklist'),
        ),
        migrations.AlterField(
            model_name='itemchecklisthistorique',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Item concerné par la modification (NULL si supprimé)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique', to='ventes.itemchecklist'),
        ),
        migrations.AlterField(
            model_name='itemchecklisthistorique',
            name='objet_nom',
            field=models.CharField(help_text="Nom de l'objet (sauvegardé en cas de suppression)", max_length=200),
        ),
        migrations.AlterField(
            model_name='itemchecklisthistorique',
            name='objet_unite',
            field=models.CharField(default='unité', help_text="Unité de l'objet", max_length=50),
        ),
        migrations.AddIndex(
            model_name='itemchecklisthistorique',
            index=models.Index(fields=['type_modification', '-date_modification'], name='ventes_item_type_mo_c82bb5_idx'),
        ),
    ]
