# Generated by Django 4.2.23 on 2025-10-12 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventes', '0009_remove_itemchecklisthistorique_ventes_item_item_id_4359ca_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_soumission', models.CharField(help_text='Numéro unique de soumission', max_length=20, unique=True)),
                ('date_evenement', models.DateField(verbose_name="Date de l'événement")),
                ('nom_compagnie', models.CharField(max_length=200, verbose_name='Nom de la compagnie')),
                ('nombre_personnes', models.PositiveIntegerField(verbose_name='Nombre de personnes')),
                ('adresse', models.TextField(verbose_name="Adresse de l'événement")),
                ('avec_service', models.BooleanField(default=False, verbose_name='Avec service')),
                ('location_materiel', models.BooleanField(default=False, verbose_name='Location matériel')),
                ('avec_alcool', models.BooleanField(default=False, verbose_name='Avec alcool')),
                ('commande_par', models.CharField(max_length=200, verbose_name='Commandé par')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_cours', max_length=20)),
                ('cree_a', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé à')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_soumission', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('notes_client', models.TextField(blank=True, verbose_name='Notes pour le client')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soumissions_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Soumission',
                'verbose_name_plural': 'Soumissions',
                'ordering': ['-date_evenement', '-cree_a'],
            },
        ),
    ]
