# Generated by Django 4.2.23 on 2025-10-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0010_soumission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soumission',
            name='notes_client',
        ),
    ]
