# Generated by Django 4.2.23 on 2025-10-14 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventes', '0011_remove_soumission_notes_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='contrats/documents/%Y/%m/', verbose_name='Fichier')),
                ('type_document', models.CharField(choices=[('soumission', 'Soumission'), ('menu', 'Menu'), ('plan_salle', 'Plan de salle'), ('contrat_signe', 'Contrat signé'), ('facture', 'Facture'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type de document')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='Titre du document')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_upload', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'upload")),
                ('taille_fichier', models.IntegerField(default=0, help_text='Taille en octets')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hotel.contrat')),
                ('uploade_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_contrats_uploades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document de contrat',
                'verbose_name_plural': 'Documents de contrats',
                'ordering': ['-date_upload'],
            },
        ),
    ]
