# Generated by Django 4.2.23 on 2025-10-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0012_documentcontrat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentContrat',
        ),
    ]
