# Generated by Django 4.2.23 on 2025-10-05 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=300)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('obligatoire', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Item Checklist',
                'verbose_name_plural': 'Items Checklist',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Template Checklist',
                'verbose_name_plural': 'Templates Checklist',
                'ordering': ['nom'],
            },
        ),
    ]
