# Generated by Django 4.2.23 on 2025-10-06 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0007_alter_livraison_checklist'),
        ('checklist', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklisttemplate',
            name='cree_par',
        ),
        migrations.DeleteModel(
            name='ChecklistItem',
        ),
        migrations.DeleteModel(
            name='ChecklistTemplate',
        ),
    ]
