# Generated by Django 4.2.23 on 2025-10-08 03:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livraison', '0008_alter_livraison_ville'),
        ('ventes', '0007_checklist_livraison'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_contrat', models.CharField(max_length=50, unique=True)),
                ('nom_evenement', models.CharField(max_length=300)),
                ('client_nom', models.CharField(max_length=200)),
                ('client_telephone', models.CharField(max_length=20)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('contact_sur_site', models.CharField(blank=True, max_length=200)),
                ('adresse_complete', models.TextField()),
                ('ville', models.CharField(default='Montréal', max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('date_evenement', models.DateField()),
                ('heure_debut_prevue', models.TimeField()),
                ('heure_fin_prevue', models.TimeField()),
                ('deroule_evenement', models.TextField(blank=True, help_text="Description détaillée du déroulement de l'événement")),
                ('nb_convives', models.PositiveIntegerField(default=0)),
                ('informations_supplementaires', models.TextField(blank=True)),
                ('instructions_speciales', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('heure_debut_reelle', models.DateTimeField(blank=True, null=True)),
                ('heure_fin_reelle', models.DateTimeField(blank=True, null=True)),
                ('rapport_boissons', models.TextField(blank=True, help_text='Rapport sur la consommation de boissons')),
                ('notes_finales', models.TextField(blank=True, help_text='Notes et remarques à la fin du contrat')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('checklist', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrat', to='ventes.checklist')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_crees', to=settings.AUTH_USER_MODEL)),
                ('livraison', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrat', to='livraison.livraison')),
                ('maitre_hotel', models.ForeignKey(limit_choices_to={'role': 'maitre_hotel'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_maitre_hotel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['date_evenement', 'heure_debut_prevue'],
            },
        ),
        migrations.CreateModel(
            name='PhotoContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contrats/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hotel.contrat')),
            ],
            options={
                'verbose_name': 'Photo de contrat',
                'verbose_name_plural': 'Photos de contrat',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('debut', 'Début du contrat'), ('fin', 'Fin du contrat'), ('rapport_boissons', 'Rapport boissons ajouté'), ('photo', 'Photo ajoutée'), ('annulation', 'Annulation')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='hotel.contrat')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de contrat',
                'verbose_name_plural': 'Historiques de contrats',
                'ordering': ['-date_action'],
            },
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['date_evenement', 'status'], name='hotel_contr_date_ev_1df1b5_idx'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['maitre_hotel', 'status'], name='hotel_contr_maitre__7f08f2_idx'),
        ),
    ]
