# Generated by Django 4.2.23 on 2025-10-05 07:49

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibiliteLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_dispo', models.CharField(choices=[('disponible', 'Disponible'), ('indisponible', 'Indisponible'), ('conge', 'Congé'), ('maladie', 'Maladie')], max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Disponibilité livreur',
                'verbose_name_plural': 'Disponibilités livreurs',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ImportExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='imports/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])])),
                ('date_import', models.DateTimeField(default=django.utils.timezone.now)),
                ('nb_lignes_total', models.IntegerField(default=0)),
                ('nb_lignes_importees', models.IntegerField(default=0)),
                ('nb_erreurs', models.IntegerField(default=0)),
                ('rapport_erreurs', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Import Excel',
                'verbose_name_plural': 'Imports Excel',
                'ordering': ['-date_import'],
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_livraison', models.CharField(max_length=50, unique=True)),
                ('client_nom', models.CharField(max_length=200)),
                ('client_telephone', models.CharField(blank=True, max_length=20)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('adresse_complete', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('date_livraison', models.DateField()),
                ('periode', models.CharField(choices=[('matin', 'Matin (5h-9h)'), ('midi', 'Midi (9h30-12h30)'), ('apres_midi', 'Après-midi (13h-20h)')], max_length=20)),
                ('heure_souhaitee', models.TimeField(blank=True, null=True)),
                ('heure_livraison_reelle', models.DateTimeField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('besoin_cafe', models.BooleanField(default=False)),
                ('besoin_the', models.BooleanField(default=False)),
                ('besoin_sac_glace', models.BooleanField(default=False)),
                ('besoin_part_chaud', models.BooleanField(default=False)),
                ('autres_besoins', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('non_assignee', 'Non assignée'), ('assignee', 'Assignée'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='non_assignee', max_length=20)),
                ('instructions_speciales', models.TextField(blank=True)),
                ('notes_internes', models.TextField(blank=True)),
                ('est_recuperation', models.BooleanField(default=False)),
                ('signature_client', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('nom_signataire', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synced_mobile', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['date_livraison', 'periode', 'heure_souhaitee'],
            },
        ),
        migrations.CreateModel(
            name='LivraisonRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Livraison dans route',
                'verbose_name_plural': 'Livraisons dans routes',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ModeEnvoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(default='#3B82F6', max_length=7)),
                ('permet_recuperation', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Mode d'envoi",
                'verbose_name_plural': "Modes d'envoi",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PhotoLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='livraisons/%Y/%m/%d/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Photo de livraison',
                'verbose_name_plural': 'Photos de livraison',
                'ordering': ['date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('periode', models.CharField(choices=[('matin', 'Matin (5h-9h)'), ('midi', 'Midi (9h30-12h30)'), ('apres_midi', 'Après-midi (13h-20h)')], max_length=20)),
                ('heure_depart', models.TimeField()),
                ('heure_retour_prevue', models.TimeField(blank=True, null=True)),
                ('heure_retour_reelle', models.TimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('ordre_livraisons', models.JSONField(blank=True, default=list)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['date', 'heure_depart'],
            },
        ),
    ]
