# Generated by Django 4.2.23 on 2025-10-05 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livraison', '0001_initial'),
        ('checklist', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='livreurs',
            field=models.ManyToManyField(limit_choices_to={'role': 'livreur'}, related_name='routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photolivraison',
            name='livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='livraison.livraison'),
        ),
        migrations.AddField(
            model_name='photolivraison',
            name='prise_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livraisonroute',
            name='livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraison.livraison'),
        ),
        migrations.AddField(
            model_name='livraisonroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraison.route'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='checklist.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livraison',
            name='livraison_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recuperations', to='livraison.livraison'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='mode_envoi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='livraison.modeenvoi'),
        ),
        migrations.AddField(
            model_name='importexcel',
            name='importe_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disponibilitelivreur',
            name='livreur',
            field=models.ForeignKey(limit_choices_to={'role': 'livreur'}, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='livraisonroute',
            unique_together={('livraison', 'route')},
        ),
        migrations.AddIndex(
            model_name='livraison',
            index=models.Index(fields=['date_livraison', 'periode'], name='livraison_l_date_li_2f62a7_idx'),
        ),
        migrations.AddIndex(
            model_name='livraison',
            index=models.Index(fields=['status'], name='livraison_l_status_1065ec_idx'),
        ),
    ]
