# Generated by Django 4.2.23 on 2025-10-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='nb_convives',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livraison',
            name='nom_evenement',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='livraison',
            name='place_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
