# Generated by Django 4.2.23 on 2025-10-05 09:51

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0003_livraison_nb_convives_livraison_nom_evenement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livraisonroute',
            options={'ordering': ['ordre']},
        ),
        migrations.AlterUniqueTogether(
            name='livraisonroute',
            unique_together={('route', 'livraison')},
        ),
        migrations.AddField(
            model_name='livraisonroute',
            name='date_ajout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='place_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='livraisonroute',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
