# Generated by Django 4.2.23 on 2025-10-05 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livraison', '0004_alter_livraisonroute_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='app',
            field=models.CharField(blank=True, max_length=20, verbose_name='Appartement'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='contact_sur_site',
            field=models.CharField(blank=True, max_length=200, verbose_name='Personne à contacter'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='informations_supplementaires',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='ligne_adresse_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ligne adresse 2'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='nom_conseiller',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livreur_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
            },
        ),
    ]
