# Generated by Django 4.2.23 on 2025-10-06 01:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0005_livraison_app_livraison_contact_sur_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50, verbose_name='Marque')),
                ('modele', models.CharField(max_length=50, verbose_name='Modèle')),
                ('annee', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Année')),
                ('immatriculation', models.CharField(max_length=20, unique=True, verbose_name='Immatriculation')),
                ('numero_chassis', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='Numéro de chassis (VIN)')),
                ('type_vehicule', models.CharField(choices=[('voiture', 'Voiture'), ('moto', 'Moto'), ('camion', 'Camion'), ('van', 'Van'), ('suv', 'SUV')], default='voiture', max_length=20, verbose_name='Type de véhicule')),
                ('carburant', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Électrique'), ('hybride', 'Hybride'), ('gpl', 'GPL')], default='essence', max_length=20, verbose_name='Type de carburant')),
                ('couleur', models.CharField(max_length=30, verbose_name='Couleur')),
                ('nombre_places', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Nombre de places')),
                ('kilometrage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kilométrage (km)')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('loue', 'Loué'), ('maintenance', 'En maintenance'), ('indisponible', 'Indisponible')], default='disponible', max_length=20, verbose_name='Statut')),
                ('prix_journalier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix journalier (€)')),
                ('date_acquisition', models.DateField(blank=True, null=True, verbose_name="Date d'acquisition")),
                ('date_derniere_revision', models.DateField(blank=True, null=True, verbose_name='Date de dernière révision')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['immatriculation'], name='livraison_v_immatri_b0c5ca_idx'), models.Index(fields=['statut'], name='livraison_v_statut_484e04_idx')],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='livraison.vehicule'),
        ),
    ]
