# Generated by Django 4.2.23 on 2025-10-06 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
        ('livraison', '0006_vehicule_route_vehicule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='ventes.checklist'),
        ),
    ]
