# Generated by Django 4.2.23 on 2025-10-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0007_alter_livraison_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='ville',
            field=models.CharField(default='Montréal', max_length=100),
        ),
    ]
