# Generated by Django 4.2.23 on 2025-10-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0008_alter_livraison_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='geocode_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livraison',
            name='geocode_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué')], default='pending', max_length=20),
        ),
    ]
