# Generated by Django 4.2.23 on 2025-10-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0009_livraison_geocode_attempts_livraison_geocode_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
