# Generated by Django 4.2.23 on 2025-10-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0010_livraison_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilitelivreur',
            name='heure_debut_shift',
            field=models.TimeField(blank=True, help_text='Heure à laquelle le livreur commence sa journée', null=True, verbose_name='Heure de début de shift'),
        ),
    ]
