# Generated by Django 4.2.23 on 2025-10-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0011_disponibilitelivreur_heure_debut_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='heure_depart',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
