# Generated by Django 4.2.23 on 2025-10-16 01:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0012_alter_route_heure_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilitelivreur',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
