# Generated by Django 4.2.23 on 2025-10-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0013_alter_disponibilitelivreur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilitelivreur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
