# Generated by Django 4.2.23 on 2025-10-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0014_alter_disponibilitelivreur_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilitelivreur',
            name='heure_fin_shift',
            field=models.TimeField(blank=True, help_text='Heure à laquelle le livreur termine sa journée', null=True, verbose_name='Heure de fin de shift'),
        ),
    ]
